import Link from 'next/link';
import {ArrowRight,BarChart3,Boxes,Receipt,Users,CheckCircle2} from 'lucide-react';

const features=[
  ['Sales dashboard','See today’s sales, monthly revenue, profit and trends in one view.',BarChart3],
  ['Expense tracking','Record purchases, operating expenses and payment methods without spreadsheets.',Receipt],
  ['Inventory control','Monitor stock levels, low-stock alerts, prices and product value.',Boxes],
  ['Customer ledger','Track purchases, payments, due balances and friendly reminders.',Users],
];

export default function SmeFeaturesPage(){return <main className="min-h-screen bg-[#f8faf9]"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="text-xl font-bold">nepal<span className="text-[#139b70]">fi</span></Link><div className="flex items-center gap-3"><Link href="/smes" className="rounded-xl px-3 py-2 text-sm font-semibold text-[#71817b]">SME overview</Link><Link href="/register" className="rounded-xl bg-[#139b70] px-4 py-2.5 text-sm font-bold text-white">Get started</Link></div></nav><section className="mx-auto max-w-6xl px-6 pb-20 pt-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#139b70]">NepalFi for SMEs</p><h1 className="mt-4 max-w-3xl text-5xl font-bold tracking-[-.06em] text-[#102a27] md:text-6xl">The everyday toolkit for a healthier business.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#71817b]">Designed around the real rhythm of Nepali small businesses: a sale, a purchase, a stock check, a customer balance and a report at the end of the month.</p><div className="mt-12 grid gap-4 md:grid-cols-2">{features.map(([title,description,Icon])=><article className="rounded-2xl border border-[#e7eeeb] bg-white p-6" key={title as string}><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e4f6ed] text-[#139b70]"><Icon size={20}/></div><CheckCircle2 size={18} className="text-[#b4dccc]"/></div><h2 className="mt-6 text-xl font-bold">{title as string}</h2><p className="mt-2 leading-6 text-[#71817b]">{description as string}</p><Link href="/dashboard/business" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#139b70]">See it in the dashboard <ArrowRight size={15}/></Link></article>)}</div><div className="mt-12 flex flex-col justify-between gap-5 rounded-2xl bg-[#102a27] p-7 text-white md:flex-row md:items-center"><div><h2 className="text-2xl font-bold">Ready to make business simpler?</h2><p className="mt-2 text-sm text-[#a8c0b8]">Start with realistic demo data and grow into a better system.</p></div><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#102a27]">Create business account <ArrowRight size={15}/></Link></div></section></main>}
